apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: index.docker.io/jenkins
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: demo-app-management
  selector:
    app: demo-app
  type: LoadBalancer
